-- Song-play report from Umami analytics (Neon project: shiny-sunset-93833202, umami-analytics).
--
-- Double-counting correction: before commit b16d316 (deployed 2026-06-02 23:09 UTC),
-- manually-clicked plays fired the song-play event twice (click handler + isActive
-- effect), while auto-advance plays fired once. So pre-fix data is NOT uniformly 2x.
-- The reliable correction is the gap dedup below: drop any song-play that repeats the
-- same session + artist + title within 2 seconds of the previous one. Empirically this
-- removes 400/862 pre-fix events and 1/35 post-fix (a client on cached old JS).
--
-- "First page" = the app's default view (sorted by times-played, 50 per page). Plays of
-- those songs are expected; everything else is genuine exploration. The key list below
-- is generated by analytics/first_page.js (replicates Explorer.tsx normalisation,
-- including the normalize-vs-normalizeArtistKey sort-lookup quirk). Regenerate it if
-- songs.json or the default sort changes:  node analytics/first_page.js

WITH plays AS (
  SELECT e.event_id, e.session_id, e.created_at,
    max(d.string_value) FILTER (WHERE d.data_key='artist') AS artist,
    max(d.string_value) FILTER (WHERE d.data_key='title') AS title
  FROM website_event e
  JOIN event_data d ON d.website_event_id = e.event_id
  WHERE e.website_id = '65225d81-5bcd-43f3-8f8c-f72ad5c48d50'  -- Matinee Idle
    AND e.event_name = 'song-play'
  GROUP BY 1, 2, 3
), deduped AS (
  SELECT * FROM (
    SELECT *,
      EXTRACT(EPOCH FROM created_at - lag(created_at) OVER (
        PARTITION BY session_id, artist, title ORDER BY created_at)) AS gap_s
    FROM plays
  ) g
  WHERE gap_s IS NULL OR gap_s >= 2  -- drop double-fired duplicates
), keyed AS (
  -- Same normalisation as Explorer.tsx normalizeArtistKey(), applied to artist and title
  SELECT *,
    regexp_replace(lower(regexp_replace(regexp_replace(artist, '\m(feat\.?|ft\.?|featuring|with)\s+', ' ', 'gi'), '\s+(&|and|\+)\s+', ' ', 'gi')), '[^a-z0-9]', '', 'g')
    || '|||' ||
    regexp_replace(lower(regexp_replace(regexp_replace(title,  '\m(feat\.?|ft\.?|featuring|with)\s+', ' ', 'gi'), '\s+(&|and|\+)\s+', ' ', 'gi')), '[^a-z0-9]', '', 'g')
    AS song_key
  FROM deduped
), classified AS (
  SELECT *, song_key IN (
    -- BEGIN first-page keys (generated 2026-06-12 by analytics/first_page.js)
    'congresswomanmalindajacksonparker|||cousinmosquito','raywyliehubbard|||snakefarm','neilinnes|||singingasongiseasy','billygraves|||theshagistotallycool','cupidsinspiration|||myworld','jessconrad|||thispullover','ogdenedsel|||deadpuppies','slimgaillard|||howhighthemoon','arcadefire|||rococo','thesensationalalexharveyband|||next','thevestibules|||bulbousbouffant','themotors|||dancingthenightaway','spookytooth|||sunshinehelpme','thebeachboys|||cuddleup','themove|||nightoffear','burtoncummings|||standtall','elbow|||groundsfordivorce','pauldavinci|||yourbabyaintyourbabyanymore','themove|||icanhearthegrassgrow','billypreston|||thatsthewaygodplannedit','fairportconvention|||fotheringay','beautifulsouth|||dontfearthereaper','bebopdeluxe|||shipsinthenight','publicservicebroadcasting|||spitfire','thedivinecomedy|||thecompletebanker','thetemptations|||ballofconfusion','wasnotwas|||hellodadiminjail','warrenzevon|||hitsomebodythehockeysong','simondupreethebigsound|||kites','steveforbert|||romeostune','elviscostello|||watchingthedetectives','billythorpe|||inmyroom','metronomy|||thelook','thequick|||hipshakejerk','madness|||michaelcaine','faithnomore|||wecarealot','thebangles|||goingdowntoliverpool','davedeedozybeakymicktich|||lastnightinsoho','talktalk|||lifeswhatyoumakeit','theshins|||turnonme','katebush|||rubberbandgirl','bobbygoldsboro|||honey','pparnold|||ifyouthinkyouregroovy','thehighllamas|||campersincontrol','theshangrilas|||sophisticatedboomboom','fleetfoxes|||whitewinterhymnal','kateannamcgarrigle|||thebikesong','wilsonpickett|||landof1000dances','sambrown|||canigetawitness','aimeemann|||yourestupidnow'
    -- END first-page keys
  ) AS on_first_page
  FROM keyed
)
-- Discovered songs: plays of anything NOT on the default first page
SELECT min(artist) AS artist, min(title) AS title,
  count(*) AS plays,
  count(DISTINCT session_id) AS listeners,
  bool_or(on_first_page) AS on_first_page,
  min(created_at)::date AS first_played,
  max(created_at)::date AS last_played
FROM classified
GROUP BY song_key
ORDER BY on_first_page, plays DESC, listeners DESC;
