version: 2
updates:
  - package-ecosystem: npm
    directory: /explorer
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 2
